# Generated by Django 3.2 on 2022-07-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='DropDown1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='DropDown2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('dropDown1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown1')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('dataAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.dataattribute')),
                ('dropDown1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown1')),
                ('dropDown2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown2')),
            ],
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='dropDown1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown1'),
        ),
    ]
