# Generated by Django 3.2 on 2022-06-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDown2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('dropDown1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown1')),
            ],
        ),
    ]
