# Generated by Django 3.2 on 2022-06-28 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0002_dropdown2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('dropDown2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown2')),
            ],
        ),
    ]
