# Generated by Django 3.2 on 2022-07-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0002_mappedtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappedtable',
            name='entriesID',
        ),
    ]
