# Generated by Django 3.2 on 2022-07-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0003_remove_mappedtable_entriesid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappedtable',
            name='entriesID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown2'),
        ),
    ]
