# Generated by Django 3.2 on 2022-06-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0004_dataattribute_dropdown1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAttributeTye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('dataAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.dataattribute')),
            ],
        ),
    ]
