# Generated by Django 3.2 on 2022-06-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0005_dataattributetye'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataAttributeTye',
            new_name='DataAttributeType',
        ),
    ]
