# Generated by Django 3.2 on 2022-07-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0007_mappedtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataattributetype',
            name='dropDown1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown1'),
        ),
        migrations.AddField(
            model_name='dataattributetype',
            name='dropDown2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Selection.dropdown2'),
        ),
    ]
