# Generated by Django 3.2 on 2022-07-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0009_auto_20220702_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappedtable',
            name='DataEntries',
        ),
        migrations.AddField(
            model_name='mappedtable',
            name='DataAttribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Selection.dataattribute'),
        ),
    ]
